#!/usr/bin/env python3
"""Build the per-tool instruction files in platforms/ and the root Hello World copy.

Tools that do not support Agent Skills read one instruction file from a fixed location. Each
file in platforms/ is a small tool-specific header followed by a canonical guide, so the tools
cannot drift apart. Edit fieldtwin-instructions.md or api-quick-reference.md, then run this.

The root index.html is a byte-for-byte copy of the create skill's Hello World asset, kept so a
repository-root static host (for example GitHub Pages) keeps serving the current page.

Usage:
    python3 scripts/build-platform-files.py          # write platforms/*
    python3 scripts/build-platform-files.py --check  # fail if any platform file is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
FULL_GUIDE = REPOSITORY_ROOT / "fieldtwin-instructions.md"
QUICK_GUIDE = REPOSITORY_ROOT / "api-quick-reference.md"
GENERATED_NOTE = (
    "<!-- Generated by scripts/build-platform-files.py from {source}. "
    "Edit the source file, not this one. -->\n\n"
)

OPENCODE_FRONTMATTER = """---
description: FieldTwin integration development assistant — secure postMessage bridge, FieldTwin API v1.10, events, and integration patterns
model: anthropic/claude-sonnet-4-6
---

<!-- To use a different provider, change the model field above, for example
     ollama/qwen2.5-coder:32b or openrouter/meta-llama/llama-3.3-70b-instruct. -->

"""

CLAUDE_CODE_HEADER = """# FieldTwin (legacy single-file command)

> Prefer the Agent Skills: install `develop-fieldtwin-integration` and
> `create-fieldtwin-integration` into `.claude/skills/` (the install script does this). This
> file remains so older installs that copied it to `.claude/skills/fieldtwin.md` keep receiving
> correct guidance through the update script.

"""

HELLO_WORLD = REPOSITORY_ROOT / "skills/create-fieldtwin-integration/assets/hello-world/index.html"

# (output file, source file) copied unchanged
COPIES = (("index.html", HELLO_WORLD),)

# (output file, source guide, header written before the note)
TARGETS = (
    ("platforms/.cursorrules", FULL_GUIDE, ""),
    ("platforms/antigravity.md", FULL_GUIDE, ""),
    ("platforms/gemini-cli.md", FULL_GUIDE, ""),
    ("platforms/opencode.md", FULL_GUIDE, OPENCODE_FRONTMATTER),
    ("platforms/claude-code.md", FULL_GUIDE, CLAUDE_CODE_HEADER),
    ("platforms/copilot-instructions.md", QUICK_GUIDE, ""),
)


def render(source: Path, header: str) -> str:
    note = GENERATED_NOTE.format(source=source.relative_to(REPOSITORY_ROOT).as_posix())
    return header + note + source.read_text(encoding="utf-8")


def main() -> int:
    check = "--check" in sys.argv[1:]
    stale = []
    outputs = [(path, render(source, header)) for path, source, header in TARGETS]
    outputs += [(path, source.read_text(encoding="utf-8")) for path, source in COPIES]
    for relative_path, output in outputs:
        target = REPOSITORY_ROOT / relative_path
        if check:
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            if current != output:
                stale.append(relative_path)
        else:
            target.write_text(output, encoding="utf-8")
            print(f"Wrote {relative_path}")

    if stale:
        print("Stale platform files: " + ", ".join(stale), file=sys.stderr)
        print("Run: python3 scripts/build-platform-files.py", file=sys.stderr)
        return 1
    if check:
        print("Platform files are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
