#!/usr/bin/env python3
"""Build the compact api-reference.json route list from the generated v1.10 attribute catalog.

api-reference.json is a flat, attachable endpoint index for AI tools that cannot run the skill's
query script. It is derived data: edit the catalog generator, not the output.

Usage:
    python3 scripts/build-api-reference.py          # write api-reference.json
    python3 scripts/build-api-reference.py --check  # fail if api-reference.json is stale
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = (
    REPOSITORY_ROOT
    / "skills/develop-fieldtwin-integration/references/api-attributes-v1.10.json"
)
OUTPUT_PATH = REPOSITORY_ROOT / "api-reference.json"

CONVENTIONS = {
    "root": "{backendUrl}/API/v1.10/ — backendUrl and APIVersion come from the trusted loaded event; keep any base path in backendUrl.",
    "subprojectRoot": "{backendUrl}/API/v1.10/{projectId}/subProject/{qualifiedSubProjectId}/ — projectId is loaded.project; there is no '-' wildcard.",
    "qualifiedSubProjectId": "{subProjectId}:{streamId}. loaded.subProject is already qualified; if only the bare ID is known, the main stream is {id}:{id}.",
    "encoding": "encodeURIComponent every path segment, including the qualified subproject ID.",
    "authentication": "Integration JWT: 'Authorization: Bearer <token>'. Server-side account API token: 'token: <apiToken>'. Never send both; never put an API token in browser code.",
    "accountRoutes": "Account routes (/assets, /metadatadefinitions, /tags, /users, ...) sit directly under /API/v1.10/ with no account ID.",
    "metadata": "There is no per-resource /metaData route. Values arrive in each resource GET under 'metaData'; write them by PATCHing the resource with a 'metaData' array. Definitions: GET /API/v1.10/metadatadefinitions.",
    "batch": "POST {plural}/batch takes { items, globals?, totalNumberOfItems? } and returns { ids }. POST/PATCH/DELETE /batch take type-keyed envelopes. See backend-api-batch.md.",
    "responses": "Collection shapes vary by endpoint (maps keyed by ID, arrays, or wrappers). Successful PATCH/DELETE can have an empty body. Parse by status and Content-Type.",
    "fields": "This file lists routes only. Query fields with: python3 skills/develop-fieldtwin-integration/scripts/query-api-attributes.py --version v1.10 --path <path> --method <method>",
}


def to_template(path: str) -> str:
    """Render ApiDoc ':param' segments as '{param}' for readability."""

    return re.sub(r":([A-Za-z][A-Za-z0-9_]*)", r"{\1}", path)


def build() -> str:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    groups: dict[str, list[dict[str, str]]] = {}
    for operation in catalog["operations"]:
        groups.setdefault(operation.get("group") or "Other", []).append(
            {
                "method": operation["method"],
                "path": to_template(operation["path"]),
                "summary": " ".join((operation.get("title") or "").split()),
            }
        )
    for operations in groups.values():
        operations.sort(key=lambda item: (item["path"], item["method"]))

    document = {
        "$comment": (
            "Generated by scripts/build-api-reference.py from "
            "skills/develop-fieldtwin-integration/references/api-attributes-v1.10.json. Do not edit by hand."
        ),
        "apiVersion": catalog.get("apiVersion", "v1.10"),
        "catalogGeneratedOn": catalog.get("generatedOn"),
        "operationCount": len(catalog["operations"]),
        "conventions": CONVENTIONS,
        "groups": dict(sorted(groups.items())),
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    output = build()
    if "--check" in sys.argv[1:]:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if current != output:
            print("api-reference.json is stale. Run: python3 scripts/build-api-reference.py", file=sys.stderr)
            return 1
        print("api-reference.json is up to date.")
        return 0

    OUTPUT_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
